package FORMULARIOS.MODULO_SISTEMA;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 *
 * @author FadrianC
 */
public class Formulario2 extends javax.swing.JFrame {

    /**
     * Creates new form Formulario2
     */
    public Formulario2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnformulario3 = new javax.swing.JButton();
        btnformulario4A = new javax.swing.JButton();
        btnformulario5 = new javax.swing.JButton();
        btnformulario6 = new javax.swing.JButton();
        btnsalirformulario2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("MODULO DE SISTEMA");

        btnformulario3.setText("CREAR USUARIO");
        btnformulario3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnformulario3ActionPerformed(evt);
            }
        });

        btnformulario4A.setText("MODIFICAR USUARIO");
        btnformulario4A.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnformulario4AActionPerformed(evt);
            }
        });

        btnformulario5.setText("CONSULTAR USUARIO");
        btnformulario5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnformulario5ActionPerformed(evt);
            }
        });

        btnformulario6.setText("ELIMINAR USUARIO");
        btnformulario6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnformulario6ActionPerformed(evt);
            }
        });

        btnsalirformulario2.setText("SALIR");
        btnsalirformulario2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalirformulario2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnsalirformulario2)
                    .addComponent(btnformulario6)
                    .addComponent(btnformulario5)
                    .addComponent(btnformulario4A)
                    .addComponent(jLabel1)
                    .addComponent(btnformulario3))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(btnformulario3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnformulario4A)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnformulario5)
                .addGap(11, 11, 11)
                .addComponent(btnformulario6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnsalirformulario2)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnformulario3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnformulario3ActionPerformed
        Formulario3 verformulario3=new Formulario3();
        
        verformulario3.setVisible(true);
    }//GEN-LAST:event_btnformulario3ActionPerformed

    private void btnformulario4AActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnformulario4AActionPerformed
        Formulario4A verformulario4A=new Formulario4A();
        
        verformulario4A.setVisible(true);
    }//GEN-LAST:event_btnformulario4AActionPerformed

    private void btnformulario5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnformulario5ActionPerformed
        Formulario5 verformulario5=new Formulario5();
        
        verformulario5.setVisible(true);
    }//GEN-LAST:event_btnformulario5ActionPerformed

    private void btnformulario6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnformulario6ActionPerformed
        Formulario6 verformulario6=new Formulario6();
        
        verformulario6.setVisible(true);
    }//GEN-LAST:event_btnformulario6ActionPerformed

    private void btnsalirformulario2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalirformulario2ActionPerformed
        dispose();
    }//GEN-LAST:event_btnsalirformulario2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formulario2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formulario2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formulario2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formulario2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formulario2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnformulario3;
    private javax.swing.JButton btnformulario4A;
    private javax.swing.JButton btnformulario5;
    private javax.swing.JButton btnformulario6;
    private javax.swing.JButton btnsalirformulario2;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
